In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
games=pd.read_csv("steam_games.csv")


In [3]:
games.head (5)

url types  \
0    https://store.steampowered.com/app/379720/DOOM/   app   
1  https://store.steampowered.com/app/578080/PLAY...   app   
2  https://store.steampowered.com/app/637090/BATT...   app   
3    https://store.steampowered.com/app/221100/DayZ/   app   
4  https://store.steampowered.com/app/8500/EVE_On...   app   

                            name  \
0                           DOOM   
1  PLAYERUNKNOWN'S BATTLEGROUNDS   
2                     BATTLETECH   
3                           DayZ   
4                     EVE Online   

                                        desc_snippet  \
0  Now includes all three premium DLC packs (Unto...   
1  PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...   
2  Take command of your own mercenary outfit of '...   
3  The post-soviet country of Chernarus is struck...   
4  EVE Online is a community-driven spaceship MMO...   

                                      recent_reviews  \
0  Very Positive,(554),- 89% of the 554 user revi...   
1  Mixed,(6,214),- 49% of the 6,214 user reviews ...   
2  Mixed,(166),- 54% of the 166 user reviews in t...   
3  Mixed,(932),- 57% of the 932 user reviews in t...   
4  Mixed,(287),- 54% of the 287 user reviews in t...   

                                         all_reviews  release_date  \
0  Very Positive,(42,550),- 92% of the 42,550 use...  May 12, 2016   
1  Mixed,(836,608),- 49% of the 836,608 user revi...  Dec 21, 2017   
2  Mostly Positive,(7,030),- 71% of the 7,030 use...  Apr 24, 2018   
3  Mixed,(167,115),- 61% of the 167,115 user revi...  Dec 13, 2018   
4  Mostly Positive,(11,481),- 74% of the 11,481 u...   May 6, 2003   

             developer                                publisher  \
0          id Software    Bethesda Softworks,Bethesda Softworks   
1     PUBG Corporation        PUBG Corporation,PUBG Corporation   
2  Harebrained Schemes  Paradox Interactive,Paradox Interactive   
3  Bohemia Interactive  Bohemia Interactive,Bohemia Interactive   
4                  CCP                                  CCP,CCP   

                                        popular_tags  \
0  FPS,Gore,Action,Demons,Shooter,First-Person,Gr...   
1  Survival,Shooter,Multiplayer,Battle Royale,PvP...   
2  Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...   
3  Survival,Zombies,Open World,Multiplayer,PvP,Ma...   
4  Space,Massively Multiplayer,Sci-fi,Sandbox,MMO...   

                                        game_details  \
0  Single-player,Multi-player,Co-op,Steam Achieve...   
1             Multi-player,Online Multi-Player,Stats   
2  Single-player,Multi-player,Online Multi-Player...   
3  Multi-player,Online Multi-Player,Steam Worksho...   
4  Multi-player,Online Multi-Player,MMO,Co-op,Onl...   

                                           languages  achievements  \
0  English,French,Italian,German,Spanish - Spain,...          54.0   
1  English,Korean,Simplified Chinese,French,Germa...          37.0   
2                      English,French,German,Russian         128.0   
3  English,French,Italian,German,Spanish - Spain,...           NaN   
4                      English,German,Russian,French           NaN   

                                               genre  \
0                                             Action   
1             Action,Adventure,Massively Multiplayer   
2                          Action,Adventure,Strategy   
3             Action,Adventure,Massively Multiplayer   
4  Action,Free to Play,Massively Multiplayer,RPG,...   

                                    game_description  \
0   About This Game Developed by id software, the...   
1   About This Game  PLAYERUNKNOWN'S BATTLEGROUND...   
2   About This Game  From original BATTLETECH/Mec...   
3   About This Game The post-soviet country of Ch...   
4                                  About This Game     

                                      mature_content  \
0                                                NaN   
1   Mature Content Description  The developers de...   
2                       

In [4]:
games.original_price

0        $19.99
1        $29.99
2        $39.99
3        $44.99
4          Free
          ...  
40828     $2.99
40829     $2.99
40830     $7.99
40831     $9.99
40832     $4.99
Name: original_price, Length: 40833, dtype: object

In [5]:
games['original_price'] = games['original_price'].str[1:]

In [6]:
games['original_price'] = pd.to_numeric(games['original_price'],errors='coerce')

In [7]:
games[(games['original_price'] >= 10.00) & (games['original_price'] <= 60.00)]

url types  \
0        https://store.steampowered.com/app/379720/DOOM/   app   
1      https://store.steampowered.com/app/578080/PLAY...   app   
2      https://store.steampowered.com/app/637090/BATT...   app   
3        https://store.steampowered.com/app/221100/DayZ/   app   
6      https://store.steampowered.com/app/601150/Devi...   app   
...                                                  ...   ...   
40778    https://store.steampowered.com/app/703860/GRID/   app   
40783  https://store.steampowered.com/app/914560/Cadr...   app   
40788  https://store.steampowered.com/app/915760/Aeth...   app   
40808  https://store.steampowered.com/app/911970/Last...   app   
40821  https://store.steampowered.com/app/906700/Fant...   app   

                                                    name  \
0                                                   DOOM   
1                          PLAYERUNKNOWN'S BATTLEGROUNDS   
2                                             BATTLETECH   
3                                                   DayZ   
6                                        Devil May Cry 5   
...                                                  ...   
40778                                               GRID   
40783                Cadria Item Shop - Blessing of Gods   
40788                                       Aether Drift   
40808                  Last Byte Standing Digital Deluxe   
40821  Fantasy Grounds - Pathfinder RPG - Return of t...   

                                            desc_snippet  \
0      Now includes all three premium DLC packs (Unto...   
1      PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...   
2      Take command of your own mercenary outfit of '...   
3      The post-soviet country of Chernarus is struck...   
6      The ultimate Devil Hunter is back in style, in...   
...                                                  ...   
40778  GRID is a racing experience like no other. Off...   
40783                                                NaN   
40788  Aether Drift is an Arena-Based Bullet Hell Arc...   
40808                                                NaN   
40821                                                NaN   

                                          recent_reviews  \
0      Very Positive,(554),- 89% of the 554 user revi...   
1      Mixed,(6,214),- 49% of the 6,214 user reviews ...   
2      Mixed,(166),- 54% of the 166 user reviews in t...   
3      Mixed,(932),- 57% of the 932 user reviews in t...   
6      Very Positive,(408),- 87% of the 408 user revi...   
...                                                  ...   
40778                                                NaN   
40783                                                NaN   
40788                                                NaN   
40808                                                NaN   
40821                                                NaN   

                                             all_reviews  release_date  \
0      Very Positive,(42,550),- 92% of the 42,550 use...  May 12, 2016   
1      Mixed,(836,608),- 49% of the 836,608 user revi...  Dec 21, 2017   
2      Mostly Positive,(7,030),- 71% of the 7,030 use...  Apr 24, 2018   
3      Mixed,(167,115),- 61% of the 167,115 user revi...  Dec 13, 2018   
6      Very Positive,(9,645),- 92% of the 9,645 user ...   Mar 7, 2019   
...                                                  ...           ...   
40778                                                NaN  Sep 12, 2019   
40783                                                NaN  Aug 23, 2018   
40788                                                NaN  Aug 27, 2018   
40808                                                NaN  Jul 30, 2018   
40821                                                NaN  Aug 29, 2018   

                     developer  \
0                  id Software   
1             PUBG Corporation   
2          Harebrained Schemes   
3          Bohemia Interactive   
6             CAPCOM Co., Ltd.   
... 

In [8]:
games.shape

(40833, 20)

In [9]:
games.head(3)

url types  \
0    https://store.steampowered.com/app/379720/DOOM/   app   
1  https://store.steampowered.com/app/578080/PLAY...   app   
2  https://store.steampowered.com/app/637090/BATT...   app   

                            name  \
0                           DOOM   
1  PLAYERUNKNOWN'S BATTLEGROUNDS   
2                     BATTLETECH   

                                        desc_snippet  \
0  Now includes all three premium DLC packs (Unto...   
1  PLAYERUNKNOWN'S BATTLEGROUNDS is a battle roya...   
2  Take command of your own mercenary outfit of '...   

                                      recent_reviews  \
0  Very Positive,(554),- 89% of the 554 user revi...   
1  Mixed,(6,214),- 49% of the 6,214 user reviews ...   
2  Mixed,(166),- 54% of the 166 user reviews in t...   

                                         all_reviews  release_date  \
0  Very Positive,(42,550),- 92% of the 42,550 use...  May 12, 2016   
1  Mixed,(836,608),- 49% of the 836,608 user revi...  Dec 21, 2017   
2  Mostly Positive,(7,030),- 71% of the 7,030 use...  Apr 24, 2018   

             developer                                publisher  \
0          id Software    Bethesda Softworks,Bethesda Softworks   
1     PUBG Corporation        PUBG Corporation,PUBG Corporation   
2  Harebrained Schemes  Paradox Interactive,Paradox Interactive   

                                        popular_tags  \
0  FPS,Gore,Action,Demons,Shooter,First-Person,Gr...   
1  Survival,Shooter,Multiplayer,Battle Royale,PvP...   
2  Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...   

                                        game_details  \
0  Single-player,Multi-player,Co-op,Steam Achieve...   
1             Multi-player,Online Multi-Player,Stats   
2  Single-player,Multi-player,Online Multi-Player...   

                                           languages  achievements  \
0  English,French,Italian,German,Spanish - Spain,...          54.0   
1  English,Korean,Simplified Chinese,French,Germa...          37.0   
2                      English,French,German,Russian         128.0   

                                    genre  \
0                                  Action   
1  Action,Adventure,Massively Multiplayer   
2               Action,Adventure,Strategy   

                                    game_description  \
0   About This Game Developed by id software, the...   
1   About This Game  PLAYERUNKNOWN'S BATTLEGROUND...   
2   About This Game  From original BATTLETECH/Mec...   

                                      mature_content  \
0                                                NaN   
1   Mature Content Description  The developers de...   
2                                                NaN   

                                minimum_requirements  \
0  Minimum:,OS:,Windows 7/8.1/10 (64-bit versions...   
1  Minimum:,Requires a 64-bit processor and opera...   
2  Minimum:,Requires a 64-bit processor and opera...   

                            recommended_requirements  original_price  \
0  Recommended:,OS:,Windows 7/8.1/10 (64-bit vers...           19.99   
1  Recommended:,Requires a 64-bit processor and o...           29.99   
2  Recommended:,Requires a 64-bit processor and o...           39.99   

  discount_price  
0         $14.99  
1            NaN  
2            NaN

In [10]:
games = games[['genre','game_details','popular_tags','developer','name']]

In [11]:
games.head(3)

genre  \
0                                  Action   
1  Action,Adventure,Massively Multiplayer   
2               Action,Adventure,Strategy   

                                        game_details  \
0  Single-player,Multi-player,Co-op,Steam Achieve...   
1             Multi-player,Online Multi-Player,Stats   
2  Single-player,Multi-player,Online Multi-Player...   

                                        popular_tags            developer  \
0  FPS,Gore,Action,Demons,Shooter,First-Person,Gr...          id Software   
1  Survival,Shooter,Multiplayer,Battle Royale,PvP...     PUBG Corporation   
2  Mechs,Strategy,Turn-Based,Turn-Based Tactics,S...  Harebrained Schemes   

                            name  
0                           DOOM  
1  PLAYERUNKNOWN'S BATTLEGROUNDS  
2                     BATTLETECH

In [12]:
games.dropna(inplace = True)

In [13]:
games.shape

(37114, 5)

In [14]:
games['game_ID'] = range(0,37114)

In [15]:
games.isnull().values.any()

False

In [16]:
games = games.reset_index()

In [17]:
def get_important_features(data):
    important_features = []
    for i in range(0, data.shape[0]):
        important_features.append(data['name'][i]+' '+data['developer'][i]+' '+data['popular_tags'][i]+' '+data['genre'][i]+data['game_details'][i])
        
    return important_features

In [18]:
games['important_features'] = get_important_features(games)
games.important_features.head(5)

0    DOOM id Software FPS,Gore,Action,Demons,Shoote...
1    PLAYERUNKNOWN'S BATTLEGROUNDS PUBG Corporation...
2    BATTLETECH Harebrained Schemes Mechs,Strategy,...
3    DayZ Bohemia Interactive Survival,Zombies,Open...
4    EVE Online CCP Space,Massively Multiplayer,Sci...
Name: important_features, dtype: object

In [19]:
cm = CountVectorizer().fit_transform(games['important_features'])

In [20]:
cs = cosine_similarity(cm)

In [21]:
print(cs)

[[1.         0.40406102 0.44932255 ... 0.23214286 0.52724973 0.14940358]
 [0.40406102 1.         0.34163336 ... 0.28620989 0.12427395 0.11268723]
 [0.44932255 0.34163336 1.         ... 0.34786262 0.37446305 0.1940285 ]
 ...
 [0.23214286 0.28620989 0.34786262 ... 1.         0.10984369 0.17928429]
 [0.52724973 0.12427395 0.37446305 ... 0.10984369 1.         0.11028219]
 [0.14940358 0.11268723 0.1940285  ... 0.17928429 0.11028219 1.        ]]


In [22]:
title = 'Call of Duty®: Black Ops II'
title_id = games[games.name == title]['game_ID'].values[0]

In [23]:
scores = list(enumerate(cs[title_id]))

In [24]:
sorted_scores = sorted(scores, key = lambda x:x[1], reverse = True)
sorted_scores = sorted_scores[1:]

In [25]:
j = 0
print('The 7 most recommended games to', title, 'are:\n')
for item in sorted_scores:
    game_title = games[games.game_ID == item[0]]['name'].values[0]
    print(j+1, game_title)
    j = j+1
    if j > 6:
        break

The 7 most recommended games to Call of Duty®: Black Ops II are:

1 Call of Duty®: Black Ops II - Apocalypse
2 Call of Duty®: Black Ops II - Uprising
3 Call of Duty®: Ghosts
4 Call of Duty®: Black Ops III
5 Call of Duty®: Black Ops III - Season Pass
6 Left 4 Dead 2
7 Call of Duty®: Black Ops


In [26]:
games = games.set_index('name')

In [27]:
games.loc[['Call of Duty®: Black Ops II - Apocalypse','Call of Duty®: Black Ops II - Uprising','Call of Duty®: Ghosts','Call of Duty®: Black Ops III','Call of Duty®: Black Ops III - Season Pass','Left 4 Dead 2','Call of Duty®: Black Ops'],
         ['genre','game_details','popular_tags','developer']]

genre  \
name                                                           
Call of Duty®: Black Ops II - Apocalypse              Action   
Call of Duty®: Black Ops II - Uprising                Action   
Call of Duty®: Ghosts                                 Action   
Call of Duty®: Black Ops III                Action,Adventure   
Call of Duty®: Black Ops III - Season Pass  Action,Adventure   
Left 4 Dead 2                                         Action   
Call of Duty®: Black Ops                              Action   

                                                                                 game_details  \
name                                                                                            
Call of Duty®: Black Ops II - Apocalypse    Single-player,Multi-player,Co-op,Downloadable ...   
Call of Duty®: Black Ops II - Uprising      Single-player,Multi-player,Co-op,Downloadable ...   
Call of Duty®: Ghosts                       Single-player,Multi-player,Steam Achievements,...   
Call of Duty®: Black Ops III                Single-player,Multi-player,Co-op,Steam Achieve...   
Call of Duty®: Black Ops III - Season Pass  Single-player,Multi-player,Co-op,Downloadable ...   
Left 4 Dead 2                               Single-player,Multi-player,Co-op,Steam Achieve...   
Call of Duty®: Black Ops                    Single-player,Multi-player,Co-op,Steam Achieve...   

                                                                                 popular_tags  \
name                                                                                            
Call of Duty®: Black Ops II - Apocalypse                 Action,Zombies,FPS,Multiplayer,Co-op   
Call of Duty®: Black Ops II - Uprising                   Action,Zombies,FPS,Multiplayer,Co-op   
Call of Duty®: Ghosts                       Dog,FPS,Action,Multiplayer,Shooter,First-Perso...   
Call of Duty®: Black Ops III                Multiplayer,FPS,Zombies,Shooter,Action,First-P...   
Call of Duty®: Black Ops III - Season Pass  Action,Adventure,FPS,Zombies,First-Person,Mult...   
Left 4 Dead 2                               Zombies,Co-op,FPS,Multiplayer,Shooter,Action,O...   
Call of Duty®: Black Ops                    Action,FPS,Zombies,Multiplayer,Shooter,Singlep...   

                                                       developer  
name                                                              
Call of Duty®: Black Ops II - Apocalypse                Treyarch  
Call of Duty®: Black Ops II - Uprising                  Treyarch  
Call of Duty®: Ghosts                              Infinity Ward  
Call of Duty®: Black Ops III                Treyarch,Aspyr (Mac)  
Call of Duty®: Black Ops III - Season Pass  Treyarch,Aspyr (Mac)  
Left 4 Dead 2                                              Valve  
Call of Duty®: Black Ops                                Treyarch